language: python
python:
  - '3.6'

cache: pip

install:
  - pip install codacy-coverage codecov python-coveralls
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - python setup.py test

after_success:
  - python-codacy-coverage -r coverage.xml
  - codecov
  - coveralls
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
